apiVersion: v1
kind: Service
metadata:
  name: cc
  labels:
    app: cc
    service: cc
spec:
  selector:
    app: cc
    service: cc
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP